import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "./header/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Google Lào Cai",
  description: "Generated by create next app",
};

export default function HomepageLayout({ children }) {
  return (
    <>
      <Header />
      <div style={{ marginTop: 50 }}>{children}</div>
    </>
  );
}
